//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKsemp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EKsemp.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string BtnClose {
            get {
                return ResourceManager.GetString("BtnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select your Languaje.
        /// </summary>
        public static string cmbSelectLanguaje {
            get {
                return ResourceManager.GetString("cmbSelectLanguaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        public static string convert {
            get {
                return ResourceManager.GetString("convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text derypt right!.
        /// </summary>
        public static string decryptText {
            get {
                return ResourceManager.GetString("decryptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text encrypt right!.
        /// </summary>
        public static string encrypText {
            get {
                return ResourceManager.GetString("encrypText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, Cant translate text, retry Again!.
        /// </summary>
        public static string errorMessage {
            get {
                return ResourceManager.GetString("errorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Insert a text to traduction.
        /// </summary>
        public static string errorMessageComplete {
            get {
                return ResourceManager.GetString("errorMessageComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a type of cryptography.
        /// </summary>
        public static string lblcombo {
            get {
                return ResourceManager.GetString("lblcombo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select you Languaje.
        /// </summary>
        public static string lblLanguaje {
            get {
                return ResourceManager.GetString("lblLanguaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select type of operation.
        /// </summary>
        public static string lblselect {
            get {
                return ResourceManager.GetString("lblselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce Word to Decrypt.
        /// </summary>
        public static string leyendToDecrypt {
            get {
                return ResourceManager.GetString("leyendToDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduce Word to Encrypt.
        /// </summary>
        public static string leyendToEncrypt {
            get {
                return ResourceManager.GetString("leyendToEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string maximize {
            get {
                return ResourceManager.GetString("maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string minimize {
            get {
                return ResourceManager.GetString("minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt.
        /// </summary>
        public static string swtConvertOFF {
            get {
                return ResourceManager.GetString("swtConvertOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt.
        /// </summary>
        public static string swtConvertON {
            get {
                return ResourceManager.GetString("swtConvertON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert code.
        /// </summary>
        public static string txtDecryptWaterMark {
            get {
                return ResourceManager.GetString("txtDecryptWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Insert word.
        /// </summary>
        public static string txtEncrytpWaterMark {
            get {
                return ResourceManager.GetString("txtEncrytpWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Result.
        /// </summary>
        public static string txtResponseWaterMark {
            get {
                return ResourceManager.GetString("txtResponseWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt and Decrypt.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
